import { Boolean, Record, Literal, String, Number, Array } from 'runtypes'

export const Config = Record({
  NODE_ENV: String,
  SSL_CERT_PATH: String,
  host: String,
  apiOrigin: String,
  protocol: String,
  additionalAllowedOrigins: String,
  sessionSecret: String,
  sessionCookieMaxAge: Number,
  saltRounds: Number,
  smtp: Record({
    host: String,
    port: Number,
    secure: Boolean,
    user: String,
    password: String,
  }),
  sendgrid: Record({
    apiKey: String,
    contactTemplate: String,
    verifyTemplate: String,
    resetTemplate: String,
    referralProgramTemplate: String,
    openVolunteerWelcomeTemplate: String,
    partnerVolunteerWelcomeTemplate: String,
    studentOnboardingWelcomeTemplate: String,
    studentParentGuardianCreatedAccountTemplate: String,
    teacherOnboardingWelcomeTemplate: String,
    reportedSessionAlertTemplate: String,
    referenceFormTemplate: String,
    referenceFormApologyTemplate: String,
    approvedNotOnboardedTemplate: String,
    openReadyToCoachTemplate: String,
    partnerReadyToCoachTemplate: String,
    becomeAnAmbassadorTemplate: String,
    referralSignUpCelebrationTemplate: String,
    customPartnerReadyToCoachTemplate: String,
    bannedUserAlertTemplate: String,
    referenceFollowupTemplate: String,
    rejectedPhotoSubmissionTemplate: String,
    rejectedReferenceTemplate: String,
    waitingOnReferencesTemplate: String,
    niceToMeetYouTemplate: String,
    niceToMeetYouNoSlackTemplate: String,
    weeklyHourSummaryEmailTemplate: String,
    weeklyHourSummaryIntroEmailTemplate: String,
    customWeeklyHourSummaryEmailTemplate: String,
    customWeeklyHourSummaryIntroEmailTemplate: String,
    weeklyHourSummaryApologyEmailTemplate: String,
    onboardingReminderOneTemplate: String,
    onboardingReminderTwoTemplate: String,
    onboardingReminderThreeTemplate: String,
    studentOnboardingHowItWorksTemplate: String,
    rosterStudentSetPasswordTemplate: String,
    meetOurVolunteersTemplate: String,
    studentOnboardingMissionTemplate: String,
    studentOnboardingSurveyTemplate: String,
    studentFirstSessionCongratsTemplate: String,
    studentReportedRudeTemplate: String,
    studentReportedSafetyTemplate: String,
    studentAbsentWarningTemplate: String,
    studentAbsentVolunteerApologyTemplate: String,
    studentUnmatchedApologyTemplate: String,
    studentOnlyLookingForAnswersTemplate: String,
    volunteerQuickTipsTemplate: String,
    partnerVolunteerLowHoursSelectedTemplate: String,
    volunteerFirstSessionCongratsTemplate: String,
    volunteerTenSessionMilestoneTemplate: String,
    volunteerInactiveThirtyDaysTemplate: String,
    volunteerInactiveSixtyDaysTemplate: String,
    volunteerInactiveNinetyDaysTemplate: String,
    volunteerInactiveBlackoutOverTemplate: String,
    volunteerAbsentWarningTemplate: String,
    volunteerAbsentStudentApologyTemplate: String,
    failedFirstAttemptedQuizTemplate: String,
    failedFirstAttemptedTrainingTemplate: String,
    emailSessionRecapMessage: String,
    favoritingEmail: String,
    studentReportedCoachDmTemplate: String,
    fallIncentiveEnrollmentWelcomeTemplate: String,
    fallIncentiveInvitedToEnrollReminderTemplate: String,
    fallIncentiveLeavingMoneyOnTableTemplate: String,
    qualifiedForGiftCardTemplate: String,
    stillTimeForQualifyingSessionTemplate: String,
    fallIncentiveCompletedChallengeTemplate: String,
    volunteerPositiveStudentFeedback: String,
    downloadCertificateTemplate: String,
    ambassadorCongratsTemplate: String,
    onboardingBackfillReadyToCoachEmail: String,

    unsubscribeGroup: Record({
      newsletter: Number,
      account: Number,
      volunteerSummary: Number,
      incentiveProgram: Number,
    }),
    contactList: Record({
      students: String,
      volunteers: String,
      teachers: String,
    }),
  }),
  logLevel: String,
  mail: Record({
    senders: Record({
      noreply: String,
      support: String,
      recruitment: String,
      students: String,
      volunteerManager: String,
      studentOutreachManager: String,
      corporatePartnershipsManager: String,
      crisis: String,
      programsManager: String,
      supportApp: String,
      incentive: String,
    }),
    receivers: Record({
      contact: String,
      staff: String,
      support: String,
      recruitment: String,
      students: String,
      volunteerManager: String,
      studentOutreachManager: String,
      corporatePartnershipsManager: String,
    }),
    people: Record({
      volunteerManager: Record({
        firstName: String,
        lastName: String,
      }),
      studentOutreachManager: Record({
        firstName: String,
        lastName: String,
      }),
      corporatePartnershipsManager: Record({
        firstName: String,
        lastName: String,
      }),
      programsManager: String,
      incentiveOutreach: String,
    }),
  }),
  client: Record({
    host: String,
  }),
  apiPort: Number,
  socketsPort: Number,
  socketApiKey: String,
  socketIOAdminUsername: String,
  socketIOAdminPassword: String,
  socketIOAdminUIMode: String,
  socketIOAdminUIReadOnly: Boolean,
  customVolunteerPartnerOrgs: Array(String),
  priorityMatchingPartnerOrgs: Array(String),
  priorityMatchingSponsorOrgs: Array(String),
  corporatePartnerReports: Record({
    customAnalyticsReportPartnerOrgs: Array(String),
    batchSize: Number,
  }),

  clusterServerAddress: String,

  cacheKeys: Record({
    updateTotalVolunteerHoursLastRun: String,
    waitTimeHeatMapAllSubjects: String,
    userRoleContextPrefix: String,
  }),

  // Sentry Data Source Name
  sentryDsn: String,

  // Twilio Credentials
  accountSid: String,
  authToken: String,
  sendingNumber: String,
  twilioAccountVerificationServiceSid: String,
  twilioVerificationRateLimitUniqueName: String,
  twilioVerificationRateLimitMaxRetries: Number,
  twilioVerificationRateLimitIntervalSeconds: Number,

  notificationSchedule: Array(Number),
  // voice to use to render speech
  voice: Literal('man'),

  workerQueueName: String,
  redisConnectionString: String,
  redisHost: String,
  redisPort: String,
  redisPassword: String,
  postgresHost: String,
  postgresRoHost: String,
  postgresPort: Number,
  postgresAnalyticsHost: String,
  postgresUser: String,
  postgresPassword: String,
  postgresDatabase: String,
  postgresRequireSSL: Boolean,
  firebase: Record({
    projectId: String,
  }),
  bannedServiceProviders: Array(String),
  awsS3: Record({
    accessKeyId: String,
    secretAccessKey: String,
    region: String,
    photoIdBucket: String,
    sessionPhotoBucket: String,
    moderatedScreenshareBucket: String,
    moderatedSessionImageUploadBucket: String,
    moderatedSessionWhiteboardImageUploadBucket: String,
  }),
  awsModerationToolsRegion: String,
  posthogToken: String,
  posthogPersonalApiToken: String,
  posthogFeatureFlagApiToken: String,
  posthogProjectId: String,
  azureClientId: String,
  azureTenantId: String,
  azureStorageSecret: String,
  azureSubscriptionId: String,
  whiteboardStorageAccountName: String,
  whiteboardStorageContainer: String,
  voiceMessageStorageAppId: String,
  voiceMessageStorageTenantId: String,
  voiceMessageStorageSecret: String,
  voiceMessageStorageAccountName: String,
  voiceMessageStorageContainer: String,
  assignmentsStorageAccountName: String,
  assignmentsStorageContainer: String,
  assignmentsFrontdoorHostName: String,
  appStorageAccountName: String,
  appStorageAccountAccessKey: String,
  sessionsStorageContainer: String,
  version: String,
  fileWorkRootPath: String,
  ipWhoIsApiKey: String,
  favoriteVolunteerLimit: Number,
  eligibleIncomeThreshold: Number,
  eligibleFRLThreshold: Number,
  customManualStudentPartnerOrg: String,

  // Google
  googleClientId: String,
  googleClientSecret: String,
  googleRecaptchaSecret: String,
  googleRecaptchaThreshold: Number,

  // Clever
  cleverClientId: String,
  cleverClientSecret: String,

  // ClassLink
  classlinkClientId: String,
  classlinkClientSecret: String,
  classlinkRosterApiKey: String,

  minSessionLength: Number,

  openAIModelId: String,
  openAIApiKey: String,

  subwayApiCredentials: String,
  subwayAIVisionEndpoint: String,
  subwayAIVisionApiKey: String,

  // Langfuse
  langfuseSecretKey: String,
  langfusePublicKey: String,
  langfuseBaseUrl: String,

  // Azure Content Safety
  azureContentSafetyApiKey: String,
  azureContentSafetyBaseUrl: String,

  // Moderation
  liveMediaBanInfractionScoreThreshold: Number,
  imageModerationMinConfidence: Number,
  minorDetectedEntityConfidenceThreshold: Number,
  toxicityModerationMinConfidence: Number,
  phoneNumberModerationConfidenceThreshold: Number,
  contextualModerationConfidenceThreshold: Number,
  emailModerationConfidenceThreshold: Number,
  moderateMessageTimeLimitMs: Number,
  contextualModerationBatchSize: Number,
  minimumModerationAddressConfidence: Number,
  minimumModerationLinkConfidence: Number,

  tremendousApiKey: String,
  tremendousImpactStudyCampaign: String,
  tremendousCustomFieldsCacheExpirationSeconds: Number,
  tremendousCampaignCacheExpirationSeconds: Number,

  // AWS Account ID
  awsAccountId: String,

  // AWS Chime
  awsChimeAccessKey: String,
  awsChimeSecretAccessKey: String,
  awsChimeRegion: String,
  awsChimeMeetingRecordingBucketArn: String,

  // AWS Bedrock
  awsBedrockAccessKey: String,
  awsBedrockSecretAccessKey: String,
  awsBedrockRegion: String,
  awsBedrockHaikuId: String,
  awsBedrockSonnet4Id: String,
  awsBedrockSonnet3ArnId: String,

  // Zwibbler
  zwibblerNodeUrl: String,
})
