ALTER ROLE subway WITH LOGIN PASSWORD 'Password123';
ALTER ROLE staff_ro WITH LOGIN PASSWORD 'Password123';
ALTER ROLE retool WITH LOGIN PASSWORD 'Password123';
ALTER ROLE basic_access WITH LOGIN PASSWORD 'Password123';
