-- migrate:up
CREATE TABLE IF NOT EXISTS upchieve.school_nces_metadata (
    school_id uuid PRIMARY KEY REFERENCES upchieve.schools (id),
    created_at timestamp NOT NULL,
    updated_at timestamp NOT NULL,
    school_year text,
    fipst int,
    statename text,
    st text,
    sch_name text,
    lea_name text,
    state_agency_no int,
    "union" text,
    st_leaid text,
    leaid text,
    st_schid text,
    ncessch text,
    schid int,
    mstreet1 text,
    mstreet2 text,
    mstreet3 text,
    mcity text,
    mstate text,
    mzip text,
    mzip4 text,
    lstreet1 text,
    lstreet2 text,
    lstreet3 text,
    lcity text,
    lzip text,
    lzip4 text,
    phone text,
    website text,
    sy_status int,
    sy_status_text text,
    updated_status int,
    updated_status_text text,
    effective_date text,
    sch_type int,
    sch_type_text text,
    recon_status text,
    out_of_state_flag text,
    charter_text text,
    chartauth1 text,
    chartauthn1 text,
    chartauth2 text,
    chartauthn2 text,
    nogrades text,
    g_pk_offered text,
    g_kg_offered text,
    g_1_offered text,
    g_2_offered text,
    g_3_offered text,
    g_4_offered text,
    g_5_offered text,
    g_6_offered text,
    g_7_offered text,
    g_8_offered text,
    g_9_offered text,
    g_10_offered text,
    g_11_offered text,
    g_12_offered text,
    g_13_offered text,
    g_UG_offered text,
    g_AE_offered text,
    gslo text,
    gshi text,
    level text,
    igoffered text
);

-- migrate:down
DROP TABLE IF EXISTS upchieve.school_nces_metadata CASCADE;

