-- migrate:up
ALTER TABLE upchieve.school_nces_metadata
    DROP COLUMN fipst,
    DROP COLUMN statename,
    DROP COLUMN state_agency_no,
    DROP COLUMN "union",
    DROP COLUMN st_leaid,
    DROP COLUMN st_schid,
    DROP COLUMN schid,
    DROP COLUMN mzip4,
    DROP COLUMN mstate,
    DROP COLUMN mstreet1,
    DROP COLUMN mstreet2,
    DROP COLUMN mstreet3,
    DROP COLUMN lzip4,
    DROP COLUMN lstreet1,
    DROP COLUMN lstreet2,
    DROP COLUMN lstreet3,
    DROP COLUMN phone,
    DROP COLUMN website,
    DROP COLUMN sy_status,
    DROP COLUMN sy_status_text,
    DROP COLUMN updated_status,
    DROP COLUMN updated_status_text,
    DROP COLUMN effective_date,
    DROP COLUMN sch_type,
    DROP COLUMN sch_type_text,
    DROP COLUMN recon_status,
    DROP COLUMN out_of_state_flag,
    DROP COLUMN charter_text,
    DROP COLUMN chartauth1,
    DROP COLUMN chartauthn1,
    DROP COLUMN chartauth2,
    DROP COLUMN chartauthn2,
    DROP COLUMN nogrades,
    DROP COLUMN g_pk_offered,
    DROP COLUMN g_kg_offered,
    DROP COLUMN g_1_offered,
    DROP COLUMN g_2_offered,
    DROP COLUMN g_3_offered,
    DROP COLUMN g_4_offered,
    DROP COLUMN g_5_offered,
    DROP COLUMN g_6_offered,
    DROP COLUMN g_7_offered,
    DROP COLUMN g_8_offered,
    DROP COLUMN g_9_offered,
    DROP COLUMN g_10_offered,
    DROP COLUMN g_11_offered,
    DROP COLUMN g_12_offered,
    DROP COLUMN g_13_offered,
    DROP COLUMN g_ug_offered,
    DROP COLUMN g_ae_offered,
    DROP COLUMN level,
    DROP COLUMN igoffered;

-- migrate:down
ALTER TABLE upchieve.school_nces_metadata
    ADD COLUMN fipst integer,
    ADD COLUMN statename text,
    ADD COLUMN state_agency_no integer,
    ADD COLUMN "union" text,
    ADD COLUMN st_leaid text,
    ADD COLUMN st_schid text,
    ADD COLUMN schid integer,
    ADD COLUMN mzip4 text,
    ADD COLUMN mstate text,
    ADD COLUMN mstreet1 text,
    ADD COLUMN mstreet2 text,
    ADD COLUMN mstreet3 text,
    ADD COLUMN lzip4 text,
    ADD COLUMN lstreet1 text,
    ADD COLUMN lstreet2 text,
    ADD COLUMN lstreet3 text,
    ADD COLUMN phone text,
    ADD COLUMN website text,
    ADD COLUMN sy_status integer,
    ADD COLUMN sy_status_text text,
    ADD COLUMN updated_status integer,
    ADD COLUMN updated_status_text text,
    ADD COLUMN effective_date text,
    ADD COLUMN sch_type integer,
    ADD COLUMN sch_type_text text,
    ADD COLUMN recon_status text,
    ADD COLUMN out_of_state_flag text,
    ADD COLUMN charter_text text,
    ADD COLUMN chartauth1 text,
    ADD COLUMN chartauthn1 text,
    ADD COLUMN chartauth2 text,
    ADD COLUMN chartauthn2 text,
    ADD COLUMN nogrades text,
    ADD COLUMN g_pk_offered text,
    ADD COLUMN g_kg_offered text,
    ADD COLUMN g_1_offered text,
    ADD COLUMN g_2_offered text,
    ADD COLUMN g_3_offered text,
    ADD COLUMN g_4_offered text,
    ADD COLUMN g_5_offered text,
    ADD COLUMN g_6_offered text,
    ADD COLUMN g_7_offered text,
    ADD COLUMN g_8_offered text,
    ADD COLUMN g_9_offered text,
    ADD COLUMN g_10_offered text,
    ADD COLUMN g_11_offered text,
    ADD COLUMN g_12_offered text,
    ADD COLUMN g_13_offered text,
    ADD COLUMN g_ug_offered text,
    ADD COLUMN g_ae_offered text,
    ADD COLUMN level text,
    ADD COLUMN igoffered text;

