-- migrate:up
INSERT INTO upchieve.nths_actions (name)
    VALUES ('MARKED SCHOOL AFFILIATION IN PROGRESS'), ('SUBMITTED ADVISOR CONTACT INFO'), ('ADVISOR VERIFIED'), ('SCHOOL AFFILIATION DENIED');

-- migrate:down
DELETE FROM upchieve.nths_actions
WHERE name IN ('MARKED SCHOOL AFFILIATION IN PROGRESS', 'SUBMITTED ADVISOR CONTACT INFO', 'ADVISOR VERIFIED', 'SCHOOL AFFILIATION DENIED');

