export enum FEATURE_FLAGS {
  USING_OUR_PLATFORM = 'using-our-platform',
  SESSION_RECAP_DMS = 'session-recap-dms',
  ALLOW_DMS_TO_PARTNER_STUDENTS = 'allow-dms-to-partner-students',
  PROGRESS_REPORTS = 'progress-reports',
  PROGRESS_REPORTS_VISION_AI = 'progress-reports-vision-ai',
  AI_MODERATION = 'ai-moderation',
  COLLEGE_LIST_WORKSHEET = 'college-list-worksheet',
  FALL_INCENTIVE_PROGRAM = 'fall-incentive-program',
  TEACHER_GETTING_STARTED_ASSIGNMENT = 'teacher-getting-started-assignment',
  GENERATE_SESSION_SUMMARY = 'generate-session-summary',
  GET_SESSION_SUMMARY = 'get-session-summary',
  DISPLAY_VOLUNTEER_LANGUAGES = 'display-volunteer-languages',
  SEND_AMBASSADOR_OPPORTUNITY_EMAIL = 'send-ambassador-opportunity-email',
  SEND_POSITIVE_STUDENT_FEEDBACK_EMAIL = 'send-positive-student-feedback-email',
  STUDENTS_INITIATE_DMS = 'students-initiate-dms',
  DISABLE_STUDENT_CREATION = 'disable-student-creation',
  NOTIFY_TUTOR = 'notify-tutor',
  ZWIBSERVE = 'zwibserve',
}
