export enum FEATURE_FLAGS {
  STANDARDIZED_CERTS = 'standardized-certs',
  USING_OUR_PLATFORM = 'using-our-platform',
  SESSION_RECAP_DMS = 'session-recap-dms',
  WEEKLY_SUMMARY_ALL_HOURS = 'weekly-summary-all-hours',
  SMS_VERIFICATION = 'sms-verification',
  ALLOW_DMS_TO_PARTNER_STUDENTS = 'allow-dms-to-partner-students',
  PROGRESS_REPORTS = 'progress-reports',
  PROGRESS_REPORTS_VISION_AI = 'progress-reports-vision-ai',
  AI_MODERATION = 'ai-moderation',
  COLLEGE_LIST_WORKSHEET = 'college-list-worksheet',
  FALL_INCENTIVE_PROGRAM = 'fall-incentive-program',
  AI_TUTOR_BOT_SUBJECT_MODELS = 'ai-tutor-bot-subject-models',
  TREMENDOUS_EMBDED_REWARDS = 'tremendous-embeded-rewards',
  TEACHER_GETTING_STARTED_ASSIGNMENT = 'teacher-getting-started-assignment',
}
