import { ExtractValues } from '../utils/type-utils'

export const FORMAT_INTEGRATED_MATH = {
  integratedMathOne: 'Integrated Math 1',
  integratedMathTwo: 'Integrated Math 2',
  integratedMathThree: 'Integrated Math 3',
  integratedMathFour: 'Integrated Math 4',
}

export enum TRAINING {
  UPCHIEVE_101 = 'upchieve101',
  TUTORING_SKILLS = 'tutoringSkills',
  COLLEGE_COUNSELING = 'collegeCounseling',
  SAT_STRATEGIES = 'satStrategies',
  COLLEGE_SKILLS = 'collegeSkills',
}

export enum MATH_CERTS {
  // TODO: fix typo
  PREALGREBA = 'prealgebra',
  ALGEBRA_ONE = 'algebraOne',
  ALGEBRA_TWO = 'algebraTwo',
  GEOMETRY = 'geometry',
  TRIGONOMETRY = 'trigonometry',
  PRECALCULUS = 'precalculus',
  CALCULUS_AB = 'calculusAB',
  CALCULUS_BC = 'calculusBC',
  STATISTICS = 'statistics',
}

export enum MATH_SUBJECTS {
  // TODO: fix typo
  PREALGREBA = 'prealgebra',
  ALGEBRA_ONE = 'algebraOne',
  ALGEBRA_TWO = 'algebraTwo',
  GEOMETRY = 'geometry',
  TRIGONOMETRY = 'trigonometry',
  PRECALCULUS = 'precalculus',
  CALCULUS_AB = 'calculusAB',
  CALCULUS_BC = 'calculusBC',
  STATISTICS = 'statistics',
  INTEGRATED_MATH_ONE = 'integratedMathOne',
  INTEGRATED_MATH_TWO = 'integratedMathTwo',
  INTEGRATED_MATH_THREE = 'integratedMathThree',
  INTEGRATED_MATH_FOUR = 'integratedMathFour',
}

export enum SCIENCE_CERTS {
  BIOLOGY = 'biology',
  CHEMISTRY = 'chemistry',
  PHYSICS_ONE = 'physicsOne',
  PHYSICS_TWO = 'physicsTwo',
  ENVIRONMENTAL_SCIENCE = 'environmentalScience',
}
export enum SCIENCE_SUBJECTS {
  BIOLOGY = 'biology',
  CHEMISTRY = 'chemistry',
  PHYSICS_ONE = 'physicsOne',
  PHYSICS_TWO = 'physicsTwo',
  ENVIRONMENTAL_SCIENCE = 'environmentalScience',
}

export enum COLLEGE_CERTS {
  ESSAYS = 'essays',
  FINANCIAL_AID = 'financialAid',
  SPORTS_RECRUITMENT_PLANNING = 'sportsRecruitmentPlanning',
  PLANNING = 'planning',
  APPLICATIONS = 'applications',
  COLLEGE_APPS = 'collegeApps',
  COLLEGE_PREP = 'collegePrep',
  COLLEGE_LIST = 'collegeList',
  APPLICATION_ESSAYS = 'applicationEssays',
}

export enum COLLEGE_SUBJECTS {
  ESSAYS = 'essays',
  FINANCIAL_AID = 'financialAid',
  SPORTS_RECRUITMENT_PLANNING = 'sportsRecruitmentPlanning',
  PLANNING = 'planning',
  APPLICATIONS = 'applications',
  COLLEGE_APPS = 'collegeApps',
  COLLEGE_PREP = 'collegePrep',
  COLLEGE_LIST = 'collegeList',
  APPLICATION_ESSAYS = 'applicationEssays',
}

export enum SAT_CERTS {
  SAT_MATH = 'satMath',
  SAT_READING = 'satReading',
}

export enum SAT_SUBJECTS {
  SAT_MATH = 'satMath',
  SAT_READING = 'satReading',
}

export enum READING_WRITING_CERTS {
  HUMANITIES_ESSAYS = 'humanitiesEssays',
  READING = 'reading',
  ESSAY_PLANNING = 'essayPlanning',
  ESSAY_FEEDBACK = 'essayFeedback',
}

export enum READING_WRITING_SUBJECTS {
  HUMANITIES_ESSAYS = 'humanitiesEssays',
  READING = 'reading',
  ESSAY_PLANNING = 'essayPlanning',
  ESSAY_FEEDBACK = 'essayFeedback',
}

export enum SOCIAL_STUDIES_CERTS {
  US_HISTORY = 'usHistory',
}

export enum SOCIAL_STUDIES_SUBJECTS {
  US_HISTORY = 'usHistory',
}

export const SUBJECTS = {
  ...MATH_SUBJECTS,
  ...SCIENCE_SUBJECTS,
  ...COLLEGE_SUBJECTS,
  ...SAT_SUBJECTS,
  ...READING_WRITING_SUBJECTS,
  ...SOCIAL_STUDIES_SUBJECTS,
}

export type SUBJECTS = ExtractValues<typeof SUBJECTS>

export const CERTS = {
  ...MATH_CERTS,
  ...SCIENCE_CERTS,
  ...COLLEGE_CERTS,
  ...SAT_CERTS,
  ...READING_WRITING_CERTS,
  ...SOCIAL_STUDIES_CERTS,
  ...TRAINING,
}

export type CERTS = ExtractValues<typeof CERTS>

export const CERT_UNLOCKING = {
  [MATH_CERTS.CALCULUS_BC]: [
    MATH_SUBJECTS.CALCULUS_BC,
    MATH_SUBJECTS.CALCULUS_AB,
    MATH_SUBJECTS.PRECALCULUS,
    MATH_SUBJECTS.TRIGONOMETRY,
    MATH_SUBJECTS.ALGEBRA_ONE,
    MATH_SUBJECTS.ALGEBRA_TWO,
    MATH_SUBJECTS.PREALGREBA,
  ],
  [MATH_CERTS.CALCULUS_AB]: [
    MATH_SUBJECTS.CALCULUS_AB,
    MATH_SUBJECTS.PRECALCULUS,
    MATH_SUBJECTS.TRIGONOMETRY,
    MATH_SUBJECTS.ALGEBRA_ONE,
    MATH_SUBJECTS.ALGEBRA_TWO,
    MATH_SUBJECTS.PREALGREBA,
  ],
  [MATH_CERTS.PRECALCULUS]: [
    MATH_SUBJECTS.PRECALCULUS,
    MATH_SUBJECTS.TRIGONOMETRY,
    MATH_SUBJECTS.ALGEBRA_ONE,
    MATH_SUBJECTS.ALGEBRA_TWO,
    MATH_SUBJECTS.PREALGREBA,
  ],
  [MATH_CERTS.TRIGONOMETRY]: [MATH_SUBJECTS.TRIGONOMETRY],
  [MATH_CERTS.ALGEBRA_ONE]: [
    MATH_SUBJECTS.ALGEBRA_ONE,
    MATH_SUBJECTS.PREALGREBA,
  ],
  [MATH_CERTS.ALGEBRA_TWO]: [
    MATH_SUBJECTS.ALGEBRA_TWO,
    MATH_SUBJECTS.ALGEBRA_ONE,
    MATH_SUBJECTS.PREALGREBA,
  ],
  [MATH_CERTS.PREALGREBA]: [MATH_SUBJECTS.PREALGREBA],
  [MATH_CERTS.STATISTICS]: [MATH_SUBJECTS.STATISTICS],
  [MATH_CERTS.GEOMETRY]: [MATH_SUBJECTS.GEOMETRY],
  [SCIENCE_CERTS.BIOLOGY]: [SCIENCE_SUBJECTS.BIOLOGY],
  [SCIENCE_CERTS.CHEMISTRY]: [SCIENCE_SUBJECTS.CHEMISTRY],
  [SCIENCE_CERTS.PHYSICS_ONE]: [SCIENCE_SUBJECTS.PHYSICS_ONE],
  [SCIENCE_CERTS.PHYSICS_TWO]: [SCIENCE_SUBJECTS.PHYSICS_TWO],
  [SCIENCE_CERTS.ENVIRONMENTAL_SCIENCE]: [
    SCIENCE_SUBJECTS.ENVIRONMENTAL_SCIENCE,
  ],
  [SOCIAL_STUDIES_CERTS.US_HISTORY]: [SOCIAL_STUDIES_SUBJECTS.US_HISTORY],
  [COLLEGE_CERTS.ESSAYS]: [COLLEGE_SUBJECTS.ESSAYS],
  // @note: move applications and planning to computed certs once College Counseling is added
  [COLLEGE_CERTS.APPLICATIONS]: [COLLEGE_SUBJECTS.APPLICATIONS],
  [COLLEGE_CERTS.PLANNING]: [COLLEGE_SUBJECTS.PLANNING],
  [COLLEGE_CERTS.FINANCIAL_AID]: [COLLEGE_SUBJECTS.FINANCIAL_AID],
  [COLLEGE_CERTS.COLLEGE_APPS]: [COLLEGE_SUBJECTS.COLLEGE_APPS],
  [COLLEGE_CERTS.COLLEGE_LIST]: [COLLEGE_SUBJECTS.COLLEGE_LIST],
  [COLLEGE_CERTS.COLLEGE_PREP]: [COLLEGE_SUBJECTS.COLLEGE_PREP],
  [COLLEGE_CERTS.APPLICATION_ESSAYS]: [COLLEGE_SUBJECTS.APPLICATION_ESSAYS],
  [COLLEGE_CERTS.SPORTS_RECRUITMENT_PLANNING]: [
    COLLEGE_SUBJECTS.SPORTS_RECRUITMENT_PLANNING,
  ],
  [SAT_CERTS.SAT_MATH]: [SAT_CERTS.SAT_MATH],
  [SAT_CERTS.SAT_READING]: [SAT_CERTS.SAT_READING],
  [TRAINING.COLLEGE_COUNSELING]: [SUBJECTS.PLANNING, SUBJECTS.APPLICATIONS],
  [READING_WRITING_CERTS.HUMANITIES_ESSAYS]: [
    READING_WRITING_SUBJECTS.HUMANITIES_ESSAYS,
  ],
  [READING_WRITING_CERTS.READING]: [READING_WRITING_SUBJECTS.READING],
  [READING_WRITING_CERTS.ESSAY_PLANNING]: [
    READING_WRITING_SUBJECTS.ESSAY_PLANNING,
  ],
  [READING_WRITING_CERTS.ESSAY_FEEDBACK]: [
    READING_WRITING_SUBJECTS.ESSAY_FEEDBACK,
  ],
}

export const COMPUTED_CERTS = {
  [SUBJECTS.INTEGRATED_MATH_ONE]: [
    SUBJECTS.ALGEBRA_ONE,
    MATH_CERTS.GEOMETRY,
    MATH_CERTS.STATISTICS,
  ],
  [SUBJECTS.INTEGRATED_MATH_TWO]: [
    SUBJECTS.ALGEBRA_ONE,
    MATH_CERTS.GEOMETRY,
    MATH_CERTS.STATISTICS,
    MATH_CERTS.TRIGONOMETRY,
  ],
  [SUBJECTS.INTEGRATED_MATH_THREE]: [
    MATH_CERTS.PRECALCULUS,
    MATH_CERTS.STATISTICS,
  ],
  [SUBJECTS.INTEGRATED_MATH_FOUR]: [MATH_CERTS.PRECALCULUS],
  // @note: temporarily hide these computed certs for when the college counseling course is added
  // [SUBJECTS.PLANNING]: [TRAINING.COLLEGE_COUNSELING],
  // [SUBJECTS.APPLICATIONS]: [TRAINING.COLLEGE_COUNSELING]
}

export enum SUBJECT_TYPES {
  MATH = 'math',
  SCIENCE = 'science',
  COLLEGE = 'college',
  SAT = 'sat',
  TRAINING = 'training',
  READING_WRITING = 'readingWriting',
  SOCIAL_STUDIES = 'socialStudies',
}

export const FORMAT_SUBJECT_TO_DISPLAY_NAME = {
  [MATH_SUBJECTS.ALGEBRA_ONE]: 'Algebra 1',
  [MATH_SUBJECTS.ALGEBRA_TWO]: 'Algebra 2',
  [MATH_SUBJECTS.CALCULUS_BC]: 'Calculus BC',
  [MATH_SUBJECTS.CALCULUS_AB]: 'Calculus AB',
  [MATH_SUBJECTS.INTEGRATED_MATH_ONE]: 'Integrated Math 1',
  [MATH_SUBJECTS.INTEGRATED_MATH_TWO]: 'Integrated Math 2',
  [MATH_SUBJECTS.INTEGRATED_MATH_THREE]: 'Integrated Math 3',
  [MATH_SUBJECTS.INTEGRATED_MATH_FOUR]: 'Integrated Math 4',
  [SCIENCE_SUBJECTS.PHYSICS_ONE]: 'Physics 1',
  [COLLEGE_SUBJECTS.ESSAYS]: 'College Essays',
  [SAT_SUBJECTS.SAT_MATH]: 'SAT Math',
  [SAT_SUBJECTS.SAT_READING]: 'SAT Reading',
  [READING_WRITING_SUBJECTS.HUMANITIES_ESSAYS]: 'Humanities Essays',
  [READING_WRITING_SUBJECTS.READING]: 'Reading',
  [READING_WRITING_SUBJECTS.ESSAY_PLANNING]: 'Essay Planning',
  [READING_WRITING_SUBJECTS.ESSAY_FEEDBACK]: 'Essay Feedback',
}
