import { ExtractValues } from '../utils/type-utils'

export const USER_ACTION_TYPES = <const>{
  QUIZ: 'QUIZ',
  SESSION: 'SESSION',
  ACCOUNT: 'ACCOUNT',
  ADMIN: 'ADMIN',
}
export type USER_ACTION_TYPES = ExtractValues<typeof USER_ACTION_TYPES>

export const QUIZ_USER_ACTIONS = <const>{
  STARTED: 'STARTED QUIZ',
  PASSED: 'PASSED QUIZ',
  FAILED: 'FAILED QUIZ',
  VIEWED_MATERIALS: 'VIEWED REVIEW MATERIALS',
  UNLOCKED_SUBJECT: 'UNLOCKED SUBJECT',
}
export type QUIZ_USER_ACTIONS = ExtractValues<typeof QUIZ_USER_ACTIONS>

export const SESSION_USER_ACTIONS = <const>{
  REQUESTED: 'REQUESTED SESSION',
  JOINED: 'JOINED SESSION',
  REJOINED: 'REJOINED SESSION',
  ENDED: 'ENDED SESSION',
  REPLIED_YES: 'REPLIED YES TO TEXT',
  TIMED_OUT_15_MINS: '15 MIN TIME OUT',
  TIMED_OUT_45_MINS: '45 MIN TIME OUT',
}
export type SESSION_USER_ACTIONS = ExtractValues<typeof SESSION_USER_ACTIONS>

export const ACCOUNT_USER_ACTIONS = <const>{
  CREATED: 'CREATED',
  UPDATED_AVAILABILITY: 'UPDATED AVAILABILITY',
  UPDATED_PROFILE: 'UPDATED PROFILE',
  ADDED_PHOTO_ID: 'ADDED PHOTO ID',
  ADDED_REFERENCE: 'ADDED REFERENCE',
  COMPLETED_BACKGROUND_INFO: 'COMPLETED BACKGROUND INFORMATION',
  DELETED_REFERENCE: 'DELETED REFERENCE',
  APPROVED: 'APPROVED',
  ONBOARDED: 'ONBOARDED',
  SUBMITTED_REFERENCE_FORM: 'SUBMITTED REFERENCE FORM',
  REJECTED_PHOTO_ID: 'REJECTED PHOTO ID',
  REJECTED_REFERENCE: 'REJECTED REFERENCE',
  BANNED: 'BANNED',
  DEACTIVATED: 'DEACTIVATED',
  VOLUNTEER_FAVORITED: 'VOLUNTEER FAVORITED',
  VOLUNTEER_UNFAVORITED: 'VOLUNTEER UNFAVORITED',
}
export type ACCOUNT_USER_ACTIONS = ExtractValues<typeof ACCOUNT_USER_ACTIONS>

export const USER_ACTION = {
  TYPE: USER_ACTION_TYPES,
  QUIZ: QUIZ_USER_ACTIONS,
  SESSION: SESSION_USER_ACTIONS,
  ACCOUNT: ACCOUNT_USER_ACTIONS,
}

// new format to move to from USER_ACTIONS
// user events in a [noun][verb] format
export const EVENTS = <const>{
  ACCOUNT_CREATED: 'ACCOUNT_CREATED',
  ACCOUNT_APPROVED: 'ACCOUNT_APPROVED',
  ACCOUNT_ONBOARDED: 'ACCOUNT_ONBOARDED',
  ACCOUNT_BANNED: 'ACCOUNT_BANNED',
  FRIEND_REFERRED: 'FRIEND_REFERRED',
  PHOTO_ID_REJECTED: 'PHOTO_ID_REJECTED',
  REFERENCE_DELETED: 'REFERENCE_DELETED',
  REFERENCE_REJECTED: 'REFERENCE_REJECTED',
  SESSION_JOINED: 'SESSION_JOINED',
  SESSION_MATCHED: 'SESSION_MATCHED',
  SESSION_REJOINED: 'SESSION_REJOINED',
  SUBJECT_UNLOCKED: 'SUBJECT_UNLOCKED',
  SESSION_REPLIED_YES_TO_TEXT: 'SESSION_REPLIED_YES_TO_TEXT', // @note: currently deprecated
  FLAGGED_BY_STANDARDIZED_CERTS: 'FLAGGED_BY_STANDARDIZED_CERTS',
  STUDENT_PROCRASTINATION_PREVENTION_REMINDER_QUEUED:
    'STUDENT_PROCRASTINATION_PREVENTION_REMINDER_QUEUED',
  STUDENT_PROCRASTINATION_PREVENTION_REMINDER_SENT:
    'STUDENT_PROCRASTINATION_PREVENTION_REMINDER_SENT',
  SESSION_RECAP_MESSAGE_NOTIFICATION_SENT:
    'SESSION_RECAP_MESSAGE_NOTIFICATION_SENT',
  USER_SUBMITTED_SESSION_RECAP_DM: 'USER_SUBMITTED_SESSION_RECAP_DM',
  PROGRESS_REPORT_ANALYSIS_COMPLETED: 'PROGRESS_REPORT_ANALYSIS_COMPLETED',
}
export type EVENTS = ExtractValues<typeof EVENTS>

export const USER_BAN_REASONS = <const>{
  NON_US_SIGNUP: 'non us signup',
  USED_BANNED_IP: 'used banned ip',
  SESSION_REPORTED: 'session reported',
  BANNED_SERVICE_PROVIDER: 'banned service provider',
  ADMIN: 'admin',
}
export type USER_BAN_REASONS = ExtractValues<typeof USER_BAN_REASONS>

export const IP_ADDRESS_STATUS = <const>{
  OK: 'OK',
  BANNED: 'BANNED',
}
export type IP_ADDRESS_STATUS = ExtractValues<typeof IP_ADDRESS_STATUS>

export const STATUS = <const>{
  SUBMITTED: 'submitted',
  REJECTED: 'rejected',
  APPROVED: 'approved',
}
export type STATUS = ExtractValues<typeof STATUS>

export const PHOTO_ID_STATUS = <const>{
  EMPTY: 'empty',
  SUBMITTED: STATUS.SUBMITTED,
  REJECTED: STATUS.REJECTED,
  APPROVED: STATUS.APPROVED,
}
export type PHOTO_ID_STATUS = ExtractValues<typeof PHOTO_ID_STATUS>

export const REFERENCE_STATUS = <const>{
  UNSENT: 'unsent',
  SENT: 'sent',
  SUBMITTED: STATUS.SUBMITTED,
  REJECTED: STATUS.REJECTED,
  APPROVED: STATUS.APPROVED,
}
export type REFERENCE_STATUS = ExtractValues<typeof REFERENCE_STATUS>

export enum VERIFICATION_METHOD {
  SMS = 'sms',
  EMAIL = 'email',
}

export enum ONBOARDING_STATUS {
  ONBOARDED = 'Onboarded',
  DEACTIVATED = 'Deactivated',
  INACTIVE = 'Inactive',
  IN_PROGRESS = 'In progress',
  NOT_STARTED = 'Not started',
}

export enum GRADES {
  SIXTH = '6th',
  SEVENTH = '7th',
  EIGHTH = '8th',
  NINTH = '9th',
  TENTH = '10th',
  ELEVENTH = '11th',
  TWELVETH = '12th',
  COLLEGE = 'College',
  OTHER = 'Other',
}

export const USER_ROLES = <const>{
  STUDENT: 'student',
  VOLUNTEER: 'volunteer',
  ADMIN: 'admin',
}
export type USER_ROLES_TYPE = ExtractValues<typeof USER_ROLES>
