const mongoose = require('mongoose')

const schoolSchema = new mongoose.Schema({
  SCHOOL_YEAR: String,
  FIPST: Number,
  STATENAME: String,
  ST: String,
  SCH_NAME: String,
  LEA_NAME: String,
  STATE_AGENCY_NO: Number,
  UNION: String,
  ST_LEAID: String,
  LEAID: Number,
  ST_SCHID: String,
  NCESSCH: Number,
  SCHID: Number,
  MSTREET1: String,
  MSTREET2: String,
  MSTREET3: String,
  MCITY: String,
  MSTATE: String,
  MZIP: Number,
  MZIP4: Number,
  LSTREET1: String,
  LSTREET2: String,
  LSTREET3: String,
  LCITY: String,
  LSTATE: String,
  LZIP: Number,
  LZIP4: String,
  PHONE: String,
  WEBSITE: String,
  SY_STATUS: Number,
  SY_STATUS_TEXT: String,
  UPDATED_STATUS: Number,
  UPDATED_STATUS_TEXT: String,
  EFFECTIVE_DATE: String,
  SCH_TYPE: Number,
  SCH_TYPE_TEXT: String,
  RECON_STATUS: String,
  OUT_OF_STATE_FLAG: String,
  CHARTER_TEXT: String,
  CHARTAUTH1: String,
  CHARTAUTHN1: String,
  CHARTAUTH2: String,
  CHARTAUTHN2: String,
  NOGRADES: String,
  G_PK_OFFERED: String,
  G_KG_OFFERED: String,
  G_1_OFFERED: String,
  G_2_OFFERED: String,
  G_3_OFFERED: String,
  G_4_OFFERED: String,
  G_5_OFFERED: String,
  G_6_OFFERED: String,
  G_7_OFFERED: String,
  G_8_OFFERED: String,
  G_9_OFFERED: String,
  G_10_OFFERED: String,
  G_11_OFFERED: String,
  G_12_OFFERED: String,
  G_13_OFFERED: String,
  G_UG_OFFERED: String,
  G_AE_OFFERED: String,
  GSLO: Number,
  GSHI: Number,
  LEVEL: String,
  IGOFFERED: String
})

schoolSchema.index({ 'SCH_NAME': 'text' })

module.exports = mongoose.model('School', schoolSchema)
